apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: udagram-frontend
  template:
    metadata:
      labels:
        component: udagram-frontend
    spec:
      containers:
        - name: udagram-frontend
          image: denyslins/udagram-frontend:e414b53
          ports:
            - containerPort: 8082
          resources:
            requests:
              memory: "256Mi"
              cpu: "0.25"
            limits:
              memory: "512Mi"
              cpu: "0.5"
